on:
  push:
    paths:
      - server/**
  pull_request:
  workflow_dispatch:

jobs:
  build-server:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-arm
          - linux-arm64
          - linux-x64
          - linux-musl-arm
          - linux-musl-arm64
          - linux-musl-x64
          - osx-arm64
          - osx-x64
          - win-arm64
          - win-x64
          - win-x86
        self-contained:
          - false
          - true
        include:
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
            runtime: osx-x64
          - runs-on: macos-latest
            runtime: osx-arm64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: |
          dotnet publish src -c Release -o bin \
          --sc ${{ matrix.self-contained }} \
          -r ${{ matrix.runtime }} \
          -p:DebugType=none \
          -p:PublishSingleFile=true \
          -p:Assemblyname=server
        working-directory: server

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-server-sc-${{matrix.self-contained}}-${{ matrix.runtime }}-${{ github.sha }}
          path: server/bin

  test-server:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: |
          dotnet test test/
        working-directory: server
